---
blank_issues_enabled: false
contact_links:
  - name: Friendzymes Community Chat (Discord)
    url: https://bit.ly/friendzymes_discord
    about: Need help? Want to jump in? Please let us know in chat.
